# Generated by Django 2.2.4 on 2019-11-15 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_party'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='member',
            new_name='player',
        ),
    ]
